### ISSUE TITLE
solution to the segmentation fault on gentoo

### ISSUE THREAD

**Issue by mightysilentsaint** [dpayne/cli-visualizer#108] opened 2018-10-04 08:45 UTC
if are on gentoo and you haven't compiled ncurses with the tinfo flag, it wont compile. after compiling ncurses with tinfo flag, you can run the install.sh and it will successfully compile but it will give you a segmentation fault error when you run vis.

to fix that:

1. make sure you have `ccache` and `clang` installed on your gentoo system
2. run `USE=tinfo emerge ncurses` to compile `ncurses` with `tinfo` use flag enabled
3. clone the git repo with `git clone https://github.com/blshkv/cli-visualizer.git`
4. `cd` to the cloned repo
5. edit the `Makefile` with the editor of your choice
6. find the line `LIBS += -ltinfo` and change it with:
```
ifdef VIS_NCURSES_LIB_PATH
	LIBS += -ltinfow
else
#if this box has an older version of ncurses
ifneq ("$(wildcard /usr/include/ncursesw/ncurses.h)","")
	LIBS += -ltinfow
else
ifdef VIS_NCURSESW
	LIBS += -ltinfow
else
	LIBS += -ltinfo
endif
endif
endif
```
7. run `./install.sh` to compile cli-visualizer
8. run `vis` to see it working

**Comment by HenkPoley** [comment] 2018-10-04 09:02
For reference, this is the same fix as discussed here: 
https://github.com/dpayne/cli-visualizer/issues/94#issuecomment-426929037

As collaboratively 'discovered' in the reddit thread mentioned over there.

**Comment by mightysilentsaint** [comment] 2018-10-05 13:59
> For reference, this is the same fix as discussed here:
> [#94 (comment)](https://github.com/dpayne/cli-visualizer/issues/94#issuecomment-426929037)
> 
> As collaboratively 'discovered' in the reddit thread mentioned over there.

i didn't mean to leave you out, sorry if it sounded like that.

**Comment by dpayne** [comment] 2018-10-07 23:44
Closing this since it's a duplicate of the other issue. Also I _think_ the issue is fixed on gentoo, although it looks like the fix might have broken debian builds.

**Closed by dpayne** 2018-10-07 23:44 UTC
