### ISSUE TITLE
Spectrum visualizer issue after update ncurses lib on Archlinux

### ISSUE THREAD

**Issue by dasnoopy** [dpayne/cli-visualizer#62] opened 2017-09-12 12:29 UTC
Not sure if it is a cli-visualizer issue or not  .. feel free to close it then...

...with latest ncurses lib update (6.0-20170902) on archlinux, , spectrum analyzer is messed up (while lorenz and ellipse visualizers are ok):

![ncurses](https://user-images.githubusercontent.com/296922/30246667-11c1d8f6-9601-11e7-91af-727fe3f3268c.png)

- Downgrading ncurses to 6.0-20170527 solve the issue.  I mean that  everything works normally

[here](https://git.archlinux.org/svntogit/packages.git/log/trunk?h=packages/ncurses) the arch linux page about changes between ncurses versions:   
There's also a thread on Archlinux forums [about](https://bbs.archlinux.org/viewtopic.php?id=229485) recent changes with ncurses lib : maybe could be useful for debug

- Issue happens with all terminal emulators I have installed (xterm, gnome-terminal 3.24.2 ant tilix from git-master)
- changing monospaced font doesn't help
- also using an ASCII char instead of an UTF-8 char  doesn't help

My Linux box
- ArchLinux 
- cli-visualizer compiled from git-master
- Xorg (but issue occurred also using wayland) and nouveau graphic drivers

If needed, let me know about  futher information

Thanks

**Comment by dpayne** [comment] 2017-09-18 06:16
It looks like the latest build of ncurses has several problems with artifacts. This maybe on my end or on ncurses end, I'll have to dig deeper. For now if anyone is having this issue the best solution is to just downgrade ncurses. It appears it has little/nothing to do with fonts or what character is used.

**Comment by dpayne** [comment] 2017-09-18 06:41
@dasnoopy I can't reproduce this on my system. Do you mind posting your full config?

**Comment by DiMakss** [comment] 2017-09-18 17:16
+1 
![bug](https://user-images.githubusercontent.com/18054997/30554692-175960a0-9cae-11e7-9f5a-276a9d09558a.png)
![cf](https://user-images.githubusercontent.com/18054997/30554737-3d16e5a6-9cae-11e7-897a-1e4034be5414.png)

**Comment by dasnoopy** [comment] 2017-09-18 17:47
@dpayne  :: these are options I  usually change compared to the default config file
```
visualizer.fps=24
audio.stereo.enabled=true
visualizer.scaling.multiplier=2.0
visualizer.spectrum.character=▋
visualizer.spectrum.bar.width=1
visualizer.spectrum.bar.spacing=0
visualizer.spectrum.smoothing.mode=sgs
```

btw , i did some test (always with latest ncurses available in archlinux) and it seems that the culprit is  `visualizer.spectrum.bar.spacing=0`  option

If I set the value to `'1'`,  things going much better even  if something weird is still noticeable

![screenshot from 2017-09-18 19-34-41](https://user-images.githubusercontent.com/296922/30555769-d3fbb2cc-9ca8-11e7-8c87-039525507e23.png) 

...very similar to  @DiMakss evidence



thanks

**Comment by dpayne** [comment] 2017-09-18 19:40
I can reproduce the issue now. There were a couple of recent changes in ncurses for wide-character support and the visualizer always writes using wide characters.

**Comment by dpayne** [comment] 2017-09-20 03:54
Running `export TERM=rxvt-256color` fixes the issue for me. This is not some I would recommend settings as a global default (e.g. in your .bashrc), but it will probably work as long as you just use it with the visualizer. For example running vis with

```
    TERM=rxvt-256color vis
```

For more details, it looks like the issue is due to some terminals that set TERM to xterm-256color compliant but do not support the ansi rep escape code. The ncurses update that changed this is here https://github.com/mirror/ncurses/commit/690589d8f19e38925db061296d4f704e4a965bb2#diff-842764d6827ee1f7e8605999bb22e2d6R4183.

**Comment by dpayne** [comment] 2017-09-21 04:10
I am closing this for now. Hopefully ncurses or the terminals fix the issue in a cleaner way, unfortunately there is not much I can do on my end. For now setting TERM to `rxvt-256color` appears to fix the issue.

**Closed by dpayne** 2017-09-21 04:10 UTC

**Comment by dasnoopy** [comment] 2017-09-21 05:11
...  thanks for the issue analysis  and explations (solution works like a charm :-)
Regards
