### ISSUE TITLE
Hangs on OSX

### ISSUE THREAD

**Issue by gteixe** [dpayne/cli-visualizer#105] opened 2018-08-31 21:50 UTC
When I try to run `./install.sh` I get the following error:

`cp /Users/gabrielteixeira/cli-visualizer/build/vis /bin/vis`
`cp: /bin/vis: Operation not permitted`
`make: *** [install] Error 1`

I followed some of the tips in other similar issues, but nothing seems to work. Unsure if it's because of the new OSX update? Thanks!

**Comment by Hursofid** [comment] 2018-09-01 15:41
Hello, I also confirm same issue, OS X 10.11.6
Steps to reproduce:

```
brew install fftw
brew install ncurses
git clone https://github.com/dpayne/cli-visualizer
cd cli-visualizer
./install
```

```cp /Users/username/cli-visualizer/build/vis /bin/vis
cp: /bin/vis: Operation not permitted
make: *** [install] Error 1
```

Any advices highly appreciated!

**Comment by Hursofid** [comment] 2018-09-01 15:53
Okay I've edited 215 line of Makefile and added '/usr/local' before '/bin/' and installation was successful

But I had a blank screen after running /usr/local/bin/vis

After I ran mkfifo /tmp/mpd.fifo and uncommented 14 line in ~/.config/vis/config and now it's just not launching, hangs after typing /usr/local/bin/vis and not doing anyting...

**Comment by dpayne** [comment] 2018-09-05 14:13
@Hursofid what does your mpd config look like?

**Comment by Hursofid** [comment] 2018-09-05 14:53
@dpayne 
```$ cat mpd.conf | sed '/^#/d;/^\s*$/d'
input {
        plugin "curl"
}```

**Comment by dpayne** [comment] 2018-09-05 17:17
@Hursofid I fixed the `/usr/local/` install issue. As for the hang after startup, I think it's due to MPD having a fifo output specified. Unfortunately, due to Mac OS limitations, `vis` cannot directly access the system audio. Instead it uses the fifo file generated by mpd. There's a more in-depth explanation here https://github.com/dpayne/cli-visualizer/issues/18. Please re-open if it still doesn't fix the issue.

**Comment by Hursofid** [comment] 2018-09-06 02:09
@dpayne 

I run ncmpcpp, enqueue to play something but /usr/bin/vis still hangs...

$ ls -l ~/.mpd ~/.ncmpcpp/
```
/Users/constructed/.mpd:
total 456
-rw-r--r--  1 constructed  staff     819 Sep  6 03:35 mpd.conf
-rw-r--r--  1 constructed  staff   12631 Sep  6 03:34 mpd.conf.bak
-rw-r--r--  1 constructed  staff   52169 Sep  6 03:37 mpd.db
-rw-r--r--  1 constructed  staff  150001 Sep  6 03:45 mpd.log
-rw-r--r--  1 constructed  staff       6 Sep  6 03:44 mpd.pid
-rw-r--r--  1 constructed  staff     300 Sep  6 03:45 mpdstate
drwxr-xr-x  2 constructed  staff      68 Sep  6 03:38 playlists

/Users/constructed/.ncmpcpp/:
total 8
-rw-r--r--  1 constructed  staff  67 Sep  6 03:43 config
-rw-r--r--  1 constructed  staff   0 Sep  6 03:42 error.log
```
$ cat ~/.mpd/mpd.conf
```
music_directory         "~/Music"
playlist_directory      "~/.mpd/playlists"
db_file                 "~/.mpd/mpd.db"
log_file                "~/.mpd/mpd.log"
pid_file                "~/.mpd/mpd.pid"
state_file              "~/.mpd/mpdstate"
auto_update             "yes"
auto_update_depth       "2"
follow_outside_symlinks "yes"
follow_inside_symlinks  "yes"

audio_output {
  type                  "osx"
  name                  "CoreAudio"
  mixer_type            "software"
}

audio_output {
  type                  "fifo"
  name                  "my_fifo"
  path                  "/tmp/mpd.fifo"
  format                "44100:16:2"
}

decoder {
  plugin                "mp4ff"
  enabled               "no"
}

bind_to_address         "127.0.0.1"
port                    "6600"

user                    "constructed"
```
$ cat ~/.ncmpcpp/config 
```
mpd_music_dir = "~/Music"
mpd_host = "localhost"
mpd_port = "6600"

**Comment by dpayne** [comment] 2018-10-08 02:50
@Hursofid is this still an issue for you? I am unable to reproduce on the latests mac os version. I'm closing this for now, since I cannot reproduce the issue. If you still have issues please let me know and I can look at it again.

**Closed by dpayne** 2018-10-08 02:50 UTC
