### ISSUE TITLE
Sending SIGUSR1 causes a segfault

### ISSUE THREAD

**Issue by nlsnightmare** [dpayne/cli-visualizer#79] opened 2018-01-16 09:22 UTC
Using the r key still works thought. Any idea why this happens?

**Comment by dpayne** [comment] 2018-01-16 18:40
I can confirm that this causes a segfault. This is pretty odd since they call the same code path. If you have time, do you mind downgrading libpulse and trying again?

**Comment by dpayne** [comment] 2018-01-18 04:17
This should now be fixed on the latest master.

**Closed by dpayne** 2018-01-18 04:17 UTC
